package sistemaoperativo;


import java.util.ArrayList;

public class PantallaInicial extends javax.swing.JFrame {
    AdministraAlgoritmos adminAlgoritmo;
    ArrayList listaProceso;
    int identificaProceso=0;
    int cont=0;
    AdministraTiempo aTiempo;
    AdministraProcesos adminProc;
    AdministraMemoria adminMemo;
    //TablaPCB tablaPCB;
    PantallaProcesos tablaDeProcesos;
    PantallaPaginas tablaDePaginas;
    int numeroPagina=0;
    int contInstrSolicitadas=1;
    DisenoProceso proc=null;
    

    /** Creates new form PantallaInicial */
    public PantallaInicial() {
        initComponents();
        tabInicial.setEnabledAt(0, true);
        tabInicial.setEnabledAt(1, true);
        tabInicial.setEnabledAt(2, true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabInicial = new javax.swing.JTabbedPane();
        PanelProcesador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_tamanoPagina = new javax.swing.JTextField();
        txt_quantum = new javax.swing.JTextField();
        btn_PanelProcesador = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbx_scheduling = new javax.swing.JComboBox();
        cbx_replacement = new javax.swing.JComboBox();
        Procesos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_cargarProceso = new javax.swing.JButton();
        btn_terminarCarga = new javax.swing.JButton();
        cbx_marcosPagina = new javax.swing.JComboBox();
        txt_Instrucciones = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbl_numProcesoP = new javax.swing.JLabel();
        Instruccion = new javax.swing.JPanel();
        btn_Random = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_tamPagina = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_tiempo = new javax.swing.JLabel();
        btn_resetBL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tama�o de p�gina");

        //Algoritmo Scheduling
        jLabel6.setText("Algoritmo Scheduling");

        jLabel2.setText("Quantum");

        btn_PanelProcesador.setText("OK");
        btn_PanelProcesador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PanelProcesadorMouseClicked(evt);
            }
        });
        
        //Algoritmo Reemplazo
        jLabel7.setText("Algoritmo Reemplazo");

        cbx_scheduling.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FIFO", "RR", "SJF", "SRT", "HRRN" }));

        cbx_replacement.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FIFO", "LRU", "LFU", "NRU", "2dC" }));

        javax.swing.GroupLayout PanelProcesadorLayout = new javax.swing.GroupLayout(PanelProcesador);
        PanelProcesador.setLayout(PanelProcesadorLayout);
        PanelProcesadorLayout.setHorizontalGroup(
            PanelProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProcesadorLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(PanelProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProcesadorLayout.createSequentialGroup()
                        .addGroup(PanelProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGroup(PanelProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelProcesadorLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(PanelProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_quantum, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                    .addComponent(txt_tamanoPagina, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                                .addGap(7, 7, 7))
                            .addGroup(PanelProcesadorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbx_replacement, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbx_scheduling, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanelProcesadorLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btn_PanelProcesador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        PanelProcesadorLayout.setVerticalGroup(
            PanelProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProcesadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_tamanoPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_quantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbx_scheduling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelProcesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbx_replacement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_PanelProcesador)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        tabInicial.addTab("Algortimo", PanelProcesador);

        Procesos.setEnabled(false);
        Procesos.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Proceso");

        //Marcos de Pagina Cargados
        jLabel4.setText("Marcos de p�gina cargados");

        btn_cargarProceso.setText("Cargar proceso");
        btn_cargarProceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cargarProcesoMouseClicked(evt);
            }
        });

        btn_terminarCarga.setText("Terminar creacion de procesos");
        btn_terminarCarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_terminarCargaMouseClicked(evt);
            }
        });

        cbx_marcosPagina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_Instrucciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_InstruccionesFocusLost(evt);
            }
        });

        jLabel5.setText("Instrucciones");

        lbl_numProcesoP.setFont(new java.awt.Font("Tahoma", 1, 14));
        lbl_numProcesoP.setText("n");

        javax.swing.GroupLayout ProcesosLayout = new javax.swing.GroupLayout(Procesos);
        Procesos.setLayout(ProcesosLayout);
        ProcesosLayout.setHorizontalGroup(
            ProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_terminarCarga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(btn_cargarProceso, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addGroup(ProcesosLayout.createSequentialGroup()
                        .addGroup(ProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ProcesosLayout.createSequentialGroup()
                                .addGroup(ProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18))
                            .addGroup(ProcesosLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGroup(ProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_Instrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                .addComponent(cbx_marcosPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_numProcesoP))))
                .addGap(48, 48, 48))
        );
        ProcesosLayout.setVerticalGroup(
            ProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProcesosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_numProcesoP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Instrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_marcosPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btn_cargarProceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_terminarCarga)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        
        //Pestaña Dato Proceso
        tabInicial.addTab("Dato Proceso", Procesos);

        btn_Random.setFont(new java.awt.Font("Tahoma", 1, 14));
        btn_Random.setText("Siguiente Instrucci�n");
        btn_Random.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RandomMouseClicked(evt);
            }
        });

        jLabel8.setText("Tama�o de pagina:");

        txt_tamPagina.setText("x");

        jLabel9.setText("Quantum:");

        txt_tiempo.setText("tiempo");

        btn_resetBL.setText("reset BL");
        btn_resetBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetBLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InstruccionLayout = new javax.swing.GroupLayout(Instruccion);
        Instruccion.setLayout(InstruccionLayout);
        InstruccionLayout.setHorizontalGroup(
            InstruccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InstruccionLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(InstruccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_resetBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Random, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InstruccionLayout.createSequentialGroup()
                        .addGroup(InstruccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InstruccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tiempo)
                            .addComponent(txt_tamPagina))))
                .addGap(31, 31, 31))
        );
        InstruccionLayout.setVerticalGroup(
            InstruccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InstruccionLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(InstruccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_tamPagina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InstruccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_tiempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btn_Random, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_resetBL)
                .addGap(14, 14, 14))
        );

        tabInicial.addTab("Ejecuci�n", Instruccion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabInicial.getAccessibleContext().setAccessibleName("Procesador");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PanelProcesadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PanelProcesadorMouseClicked
        // TODO add your handling code here:

        int tamanoPagina=Integer.parseInt(txt_tamanoPagina.getText());
        int quantum=Integer.parseInt(txt_quantum.getText());
        String scheduleAlgorithm=cbx_scheduling.getItemAt(cbx_scheduling.getSelectedIndex()).toString();
        String replaceAlgorithm=cbx_replacement.getItemAt(cbx_replacement.getSelectedIndex()).toString();
        adminAlgoritmo=new AdministraAlgoritmos( tamanoPagina, quantum, scheduleAlgorithm, replaceAlgorithm);
        tabInicial.setEnabledAt(0, true);
        tabInicial.setEnabledAt(1, true);
        tabInicial.setEnabledAt(2, true);
        tabInicial.setSelectedIndex(1);
        aTiempo = new AdministraTiempo();
        aTiempo.horaLlegada();
        lbl_numProcesoP.setText("1");
        /*if((procesador.replaceAlgorithm).equalsIgnoreCase("NRU")){
            btn_resetBL.setVisible(true);
        } else{
            btn_resetBL.setVisible(false);
        }+*/
    }//GEN-LAST:event_btn_PanelProcesadorMouseClicked

    private void txt_InstruccionesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_InstruccionesFocusLost
        // TODO add your handling code here:
        int num=0;
        try{
             num = Integer.parseInt(txt_Instrucciones.getText());
        }catch(NumberFormatException e){
        }
        if(num>0){
            int numPag = (int)(Math.ceil((double)num/(double)adminAlgoritmo.tamPag));
            cbx_marcosPagina.removeAllItems();

            for (int i = 1; i <= numPag; i++) {
                num=i;
                cbx_marcosPagina.addItem(String.valueOf(num));
            }
        }
    }//GEN-LAST:event_txt_InstruccionesFocusLost

    private void btn_cargarProcesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cargarProcesoMouseClicked
        // TODO add your handling code here:

         identificaProceso++;
         int numInst= Integer.parseInt(this.txt_Instrucciones.getText());
         int numMarcos = (Integer.parseInt(cbx_marcosPagina.getItemAt(cbx_marcosPagina.getSelectedIndex()).toString()))-1;
         int numPaginas = (int) Math.ceil((double)(numInst)/(double)(adminAlgoritmo.tamPag));
         proc = new DisenoProceso(identificaProceso, numInst, numPaginas, numMarcos, aTiempo);
         if(cont<1){
            if(identificaProceso<=1) listaProceso=new ArrayList();
            listaProceso.add(proc);
        }else{
            //btn_terminarCarga.setVisible(false);
            listaProceso.add(proc);
            //mp.procesos.add(p);
            //mp.mm.procesos.add(p);
            if((adminAlgoritmo.algoritmoScheduling.equalsIgnoreCase("SRT"))||
                    (adminAlgoritmo.algoritmoScheduling.equalsIgnoreCase("HRRN"))){
                adminProc.ejecutaProcesos();
            }
            //lbl_numProceso.setText(String.valueOf(mp.procesoActual.numProceso));
          //  tablaPCB.llenarTablaPCB(procesos,mp.procesoActual.numProceso);
        }
        lbl_numProcesoP.setText(String.valueOf(identificaProceso+1));
        txt_Instrucciones.setText("");
        cbx_marcosPagina.removeAllItems();
    }//GEN-LAST:event_btn_cargarProcesoMouseClicked

    private void btn_terminarCargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_terminarCargaMouseClicked
        // TODO add your handling code here:
        cont++;
        tabInicial.setEnabledAt(0, true);
        tabInicial.setEnabledAt(1, true);
        tabInicial.setEnabledAt(2, true);
        tabInicial.setSelectedIndex(2);
        adminProc= new AdministraProcesos(adminAlgoritmo,listaProceso,aTiempo);
        adminProc.ejecutaProcesos();
        adminProc.procesoActual.estadoProceso="Running";
        //this.lbl_numProceso.setText(String.valueOf(mp.procesoActual.numProceso));

        //tablaPCB=new TablaPCB();
        //tablaPCB.setVisible(true);
        //tablaPCB.llenarTablaPCB(procesos,mp.procesoActual.numProceso);
        tablaDeProcesos=new PantallaProcesos();
        tablaDeProcesos.setVisible(true);
        //tablaProcesos.llenarTablaProcesos(procesos);
        tablaDeProcesos.llenaTablaProcesos(listaProceso,adminAlgoritmo.algoritmoScheduling);
        
        tablaDePaginas=new PantallaPaginas();
        tablaDePaginas.setVisible(true);
        tablaDePaginas.llenaTablaPaginas(adminProc.procesoActual,adminAlgoritmo.algoritmoReemplazo);
        //tablaProcesos.llenarTablaProcesos(procesos);

        txt_tiempo.setText(String.valueOf(adminAlgoritmo.quantumSistema));
        txt_tamPagina.setText(String.valueOf(adminAlgoritmo.tamPag));

        if((adminAlgoritmo.algoritmoReemplazo).equalsIgnoreCase("NRU")){
            btn_resetBL.setVisible(true);
        } else{
            btn_resetBL.setVisible(false);
        }

        btn_terminarCarga.setVisible(false);
        
    }//GEN-LAST:event_btn_terminarCargaMouseClicked

    public static void waiting (int n){
        long t0, t1;
        
        t0 =  System.currentTimeMillis();

        do{
            t1 = System.currentTimeMillis();
            
        }
        while ((t1 - t0) < (long)(n * 100));
    }

    private void btn_RandomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RandomMouseClicked
       int i=0;
        int r=0;
        try{
            if(!listaProceso.isEmpty()){
                if(numeroPagina!=adminProc.procesoActual.idProceso){
                    numeroPagina=adminProc.procesoActual.idProceso;
                    adminProc.procesoActual.idInstr++;
                    adminProc.procesoActual.acumInstrEjecutadas++;
                }else{
                    //Si numP es igual al proceso actual
                    adminProc.procesoActual.idInstr++;
                    if(!adminProc.todosBloqueados())
                        adminProc.procesoActual.acumInstrEjecutadas++;
                }
                contInstrSolicitadas++;
                
                if(adminProc.consumeInstruccion((int)(adminProc.procesoActual.arregloSigInstr[0]))){

                    /*System.out.println("Proceso "+mp.procesoActual.numProceso+
                                    ": Cont= "+contadorInstruccionesPedidas+
                                    " - "
                                    + mp.procesoActual.instruccionSiguiente[0]+"/"
                                    +mp.procesoActual.numInstrucciones+
                                    " IPedida= "+mp.procesoActual.instruccionPedida+
                                    "  Iej: "+mp.procesoActual.instruccionesEjecutadas+
                                    " tb: "+mp.procesoActual.tiempoBloqueado+
                                    "Sig. Inst: "+ mp.procesoActual.instruccionSiguiente[1]);*/
                    tablaDeProcesos.instruccionleida(String.valueOf(adminProc.procesoActual.arregloSigInstr[0]));
                    PantallaProcesos.siguienteInstruccion(String.valueOf(adminProc.procesoActual.arregloSigInstr[1]));

                    if(numeroPagina==adminProc.procesoActual.idProceso){
                        adminProc.procesoActual.arregloSigInstr[0] = adminProc.procesoActual.arregloSigInstr[1];
                        adminProc.procesoActual.arregloSigInstr[1] = (int)((Math.random()*adminProc.procesoActual.instrXProceso+1));
                    }else{
                        tablaDeProcesos.instruccionleida("La siguiente instrucci�n es: ");
                        PantallaProcesos.siguienteInstruccion(String.valueOf(adminProc.procesoActual.arregloSigInstr[0]));
                    }
                }
                    r=adminProc.memoria.identificaReemplazo(adminProc.procesoActual, (int)adminProc.procesoActual.arregloSigInstr[0], aTiempo.tiempoSistema);
                    PantallaPaginas.cambioDePagina(r);

                    tablaDeProcesos.llenaTablaProcesos(listaProceso, adminAlgoritmo.algoritmoScheduling);
                    tablaDePaginas.llenaTablaPaginas(adminProc.procesoActual,adminAlgoritmo.algoritmoReemplazo);
            }
        }catch(NullPointerException npe){
        }
    }//GEN-LAST:event_btn_RandomMouseClicked

    private void btn_resetBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetBLMouseClicked
        // TODO add your handling code here:
        DisenoProceso p;
        for (int i = 0; i < adminProc.listaDeProcesos.size(); i++) {
            p= (DisenoProceso)adminProc.listaDeProcesos.get(i);
            for (int j = 0; j < p.pagXProceso; j++) {
                p.arregloPaginas[j].bLect=false;
            }
        }
        tablaDePaginas.llenaTablaPaginas(adminProc.procesoActual,adminAlgoritmo.algoritmoReemplazo);
}//GEN-LAST:event_btn_resetBLMouseClicked

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Instruccion;
    private javax.swing.JPanel PanelProcesador;
    private javax.swing.JPanel Procesos;
    private javax.swing.JButton btn_PanelProcesador;
    private javax.swing.JButton btn_Random;
    private javax.swing.JButton btn_cargarProceso;
    private javax.swing.JButton btn_resetBL;
    private javax.swing.JButton btn_terminarCarga;
    private javax.swing.JComboBox cbx_marcosPagina;
    private javax.swing.JComboBox cbx_replacement;
    private javax.swing.JComboBox cbx_scheduling;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_numProcesoP;
    private javax.swing.JTabbedPane tabInicial;
    private javax.swing.JTextField txt_Instrucciones;
    private javax.swing.JTextField txt_quantum;
    private javax.swing.JLabel txt_tamPagina;
    private javax.swing.JTextField txt_tamanoPagina;
    private javax.swing.JLabel txt_tiempo;
    // End of variables declaration//GEN-END:variables



}

