package sistemaoperativo;



import java.awt.Color;
import java.awt.Component;
import java.awt.Window;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author MajoCarmen
 */
public class PantallaPaginas extends javax.swing.JFrame {
    DefaultTableModel framePaginas;

    /** Creates new form TablaPaginas */
    public PantallaPaginas() {
        initComponents();
        framePaginas=new DefaultTableModel();
        framePaginas.addColumn("Num Pagina");
        framePaginas.addColumn("Bit Residencia");
        framePaginas.addColumn("Info Relevante"); 
        framePaginas.addRow(new Object []{null, null, null});
        tablaPaginas.setModel(framePaginas);
         Window[] w=PantallaProcesos.getWindows();
         w[1].setLocation(w[0].getWidth()+5, w[0].getY());

         TableColumn tcol;
         //va recrriendo las columnas
        for(int i=0;i<3;i++)
        {
            tcol= tablaPaginas.getColumnModel().getColumn(i);
            tcol.setCellRenderer(new CustomTableCellRenderer());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrolP1 = new javax.swing.JScrollPane();
        tablaPaginas = new javax.swing.JTable();
        txt_Proc = new javax.swing.JLabel();
        jEtiq1 = new javax.swing.JLabel();
        txt_PaginaACambiar = new javax.swing.JLabel();
        lbl_aux = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaPaginas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrolP1.setViewportView(tablaPaginas);

        txt_Proc.setFont(new java.awt.Font("Tahoma", 1, 14));
        txt_Proc.setText("Proceso x");

        jEtiq1.setText("Se reemplazar� la p�gina:");

        txt_PaginaACambiar.setText("--");

        lbl_aux.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrolP1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_Proc)
                        .addGap(143, 143, 143)
                        .addComponent(lbl_aux, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jEtiq1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_PaginaACambiar)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Proc)
                    .addComponent(lbl_aux))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEtiq1)
                    .addComponent(txt_PaginaACambiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrolP1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    public class CustomTableCellRenderer extends DefaultTableCellRenderer{
        @Override
        public Component getTableCellRendererComponent (JTable table,
          Object obj, boolean isSelected, boolean hasFocus, int row, int column) {
            Component cell = super.getTableCellRendererComponent(
                             table, obj, isSelected, hasFocus, row, column);
            String BR=String.valueOf(table.getValueAt(row, 1));
            if(BR.equalsIgnoreCase("true")){
                cell.setBackground(Color.green);
            }else{
                cell.setBackground(Color.white);
            }
            /*
            if (estado.equalsIgnoreCase("Running"))
            {
                cell.setBackground(Color.green);
            }
            if(estado.equalsIgnoreCase("Ready")){
                cell.setBackground(Color.white);
            }*/



            return cell;
        }
    }

    public void llenaTablaPaginas(DisenoProceso procesoActual,String replaceAlgorithm){
        //int n=procesos.size();
        int i,j,nP;
        //Proceso pr=(Proceso)procesos.get(0);
        DisenoPagina pg;
        String dato="";
        lbl_aux.setText(replaceAlgorithm);
        txt_Proc.setText("P�ginas del Proceso "+String.valueOf(procesoActual.idProceso));
        while (tablaPaginas.getRowCount() > 0) {
            ((DefaultTableModel) tablaPaginas.getModel()).removeRow(0);}

        for(i=0;i<procesoActual.arregloPaginas.length;i++){
            //pr=(Proceso) procesos.get(i);
            //nP=pr.paginas.length;
            //for(j=0;j<nP;j++){
            if(replaceAlgorithm.equalsIgnoreCase("FIFO")){
                dato=String.valueOf(procesoActual.arregloPaginas[i].tEntrada);
            }
            if(replaceAlgorithm.equalsIgnoreCase("LRU")){
                dato=procesoActual.arregloPaginas[i].tUltimaLect;
            }
            if(replaceAlgorithm.equalsIgnoreCase("LFU")){
                dato=String.valueOf(procesoActual.arregloPaginas[i].contAccesos);
            }
            if(replaceAlgorithm.equalsIgnoreCase("NRU")){
                if(procesoActual.arregloPaginas[i].bLect==true){
                    dato="1";
                }else{
                    dato="0";
                }
            }
            if(replaceAlgorithm.equalsIgnoreCase("2dC")){
                dato=String.valueOf(procesoActual.arregloPaginas[i].contAccesos);
            }
                pg=procesoActual.arregloPaginas[i];
                framePaginas.addRow(new Object [] {pg.numPag, pg.bResid,dato});
            //}
        }
    }

    public static void cambioDePagina(int pag){
        txt_PaginaACambiar.setText(String.valueOf(pag));
    }

    /*
    public void instruccionPedida(String inst){
        txt_instruccionPedida.setText(inst);
    }
     */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPaginas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jEtiq1;
    private javax.swing.JScrollPane jScrolP1;
    private javax.swing.JLabel lbl_aux;
    private javax.swing.JTable tablaPaginas;
    private javax.swing.JLabel txt_Proc;
    private static javax.swing.JLabel txt_PaginaACambiar;
    // End of variables declaration//GEN-END:variables

}

